version: '3.8'

services:
  "problematic-internet-use-api":
    user: root
    image: "problematic-internet-use-api:0.1"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      CACHE_PATH: "/code/data"
    ports:
      - "8000:8000"
    volumes:
      - ./src/api/:/code/api
      - ../problematic-internet-use-cache:/code/data
    command: fastapi dev main.py --host 0.0.0.0 --port 8000
